pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - pipe: atlassian/aws-s3-deploy:0.2.4
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-west-1'
              S3_BUCKET: 'despachito-bucket'
              LOCAL_PATH: 'build'
